import Mathlib.Data.Nat.Basic

/-!
# ProofScratch — proof attempt

Generated by scaffold/v1. Statements only: every theorem body is
`sorry` by construction, and each declaration carries the identity of the source
item it formalizes.
-/

namespace DemoNaturals

variable {a b c : ℕ}

/--
**Definition divides** — declaration id `dn-ch1-def-1.1-1`

Source: §1.1, p. 1, verbatim:

> We say that $a$ *divides* $b$, written $a \mid b$, if there is a natural number $q$ with $b = a q$.

Source ↔ Lean:
* a ∣ b: `there is a natural number $q$ with $b = a q$` → `∃ q : ℕ, b = a * q` (notation, equivalent)
-/
def Divides (a b : ℕ) : Prop :=
  ∃ q : ℕ, b = a * q

/--
**Theorem 1.1** — declaration id `dn-ch1-thm-1.1`

Source: §1.1, p. 1, verbatim:

> If $a \mid b$ and $b \mid c$, then $a \mid c$.

Source ↔ Lean:
* transitivity: `If $a \mid b$ and $b \mid c$, then $a \mid c$.` → `Divides a b → Divides b c → Divides a c` (notation, equivalent)
-/
theorem divides_trans (hab : Divides a b) (hbc : Divides b c) :
    Divides a c := by
  unfold Divides at hab hbc ⊢
  obtain ⟨q, rfl⟩ := hab
  obtain ⟨r, rfl⟩ := hbc
  exact ⟨q * r, Nat.mul_assoc a q r⟩

/--
**Theorem 1.2** — declaration id `dn-ch1-thm-1.2`

Source: §1.1, p. 1, verbatim:

> If $a \mid b$ and $a \mid c$, then $a \mid (b + c)$.

Source ↔ Lean:
* additivity: `$a \mid (b + c)$` → `Divides a (b + c)` (notation, equivalent)
-/
theorem divides_add (hab : Divides a b) (hac : Divides a c) :
    Divides a (b + c) := by
  sorry

/--
**Theorem 1.3** — declaration id `dn-ch1-thm-1.3`

Source: §1.2, p. 2, verbatim:

> If $a \mid b$ and $a \mid c$, then $a \mid (b + b + c)$.

Source ↔ Lean:
* b + b + c: `$a \mid (b + b + c)$` → `Divides a (b + b + c)` (representation, equivalent)
-/
theorem divides_add_add (hab : Divides a b) (hac : Divides a c) :
    Divides a (b + b + c) :=
  divides_add (divides_add hab hab) hac

end DemoNaturals
